[package]
name = "rust_smartpointers"
version = "0.1.0"
authors = ["ashwinsekaran"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
